function zeichne_Dreiecke(n, factor, flag)

% ZEICHNE_DREIECKE(N,FACTOR,FLAG) draws a fractal landscape 
% which is given by a recursively computed mountain in 3D -
% with or without randomisation.
% n gives the number of iterations; factor is the contraction factor;
% flag indicates whether the height difference is chosen randomly - 
% flag = 0 is random, every other flag gives the deterministic picture.
% 
% ZEICHNE_DREIECKE(N,FACTOR) plots a random mountain (flag = 0).
%
% ZEICHNE_DREIECKE uses n = 6 and factor = 0.4 in addition.

% This file was generated by students as a partial fulfillment 
% for the requirements of the course "Fractals", Winter term
% 2004/2005, Stuttgart University.	
	
% Author : Tanja Fischer, Pascal Maerkl
% Date   : Jan 2005
% Version: 1.0

% default settings
if (nargin < 3)
    flag = 0;
end
if (nargin < 2)
    n = 6;
    factor = 0.4;
end

% loading the colormap
load mat2;
colormap (map);

% compute the co-ordinates of the mountain
[x1,x2,y] = dreiecke(n, factor, flag);

% plot the results
fill3(x1', x2', y', y'/max(max(y)));
axis off;
grid off;
camlight right;
view(-40,20);

